---
- name: Automation XR - ICE
  hosts: "{{ router_var }}"
  connection: local
  gather_facts: no
  vars_files:
    - ./external_vars.yml

  tasks:
    - name: Creando configuración de nuevos policy_maps
      demo_module_03:
        var1: '{{ tabla_maps }}'
      register: nuevos_policy_maps
 
    - name: Configurando nuevos policy_maps
      cisco.iosxr.iosxr_config:
        src: "{{ nuevos_policy_maps.meta }}"

    - name: Abrir archivo de cambios
      set_fact:
        new_var: "{{ lookup('file', '/tmp/07-policy-map-changes-new.json') }}"
      #no_log: true

    - name: Respaldo policy_map Bundle{{ bundle_var }} antes de cambio
      cisco.iosxr.iosxr_command:
        commands:
        - sh policy-map targets | include "(Policy|Bundle)"
      register: antes_var 
      
    - name: Aplicar cambios en la configuración
      cisco.iosxr.iosxr_config:
        lines:
        - no service-policy input {{ item.value.in_old }}
        - service-policy input {{item.value.in_new }}
        parents: interface {{ item.key }}
      loop: "{{ new_var | dict2items }}"
      no_log: true

    - name: Respaldo policy_map Bundle{{ bundle_var }} despues del cambio
      cisco.iosxr.iosxr_command:
        commands:
        - sh policy-map targets | include "(Policy|Bundle)"
      register: despues_var 

    - name: print
      debug:
        msg: 
        - "{{ antes_var.stdout_lines }}"
        - "{{ despues_var.stdout_lines }}"
    
