---
- name: Automation XR - ICE
  hosts: "{{ router_var }}"
  connection: local
  gather_facts: no
  vars_files:
    - ./external_vars.yml

  tasks:
    - name: Respaldo Bundle {{ bundle_var }} antes de cambio
      cisco.iosxr.iosxr_command:
        commands:
        - sh bundle bundle-ether {{ bundle_var }}
      register: antes_var 

    - name: 
      cisco.iosxr.iosxr_config:
        lines:
        - shutdown
        - no bundle id {{ bundle_var }} mode on
        parents: interface {{ item }}
      loop: "{{ elementos_var }}"

    - name: Respaldo Bundle {{ bundle_var }} despues del cambio
      cisco.iosxr.iosxr_command:
        commands:
        - sh bundle bundle-ether {{ bundle_var }}
      register: despues_var 

    - name: print
      debug:
        msg: 
        - "{{ antes_var.stdout_lines }}"
        - "{{ despues_var.stdout_lines }}"
    
